spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:15432/database
    username: user
    password: pass

  flyway:
    schemas: test
    locations: classpath:db/migration
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: NON_EMPTY

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: debug
    kirimaru: trace
    org.springframework.security: trace