spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:15432/database
    username: user
    password: pass

  flyway:
    schemas: app
    default-schema: app
    locations: classpath:db/migration
  sql:
    init:
      mode: never
  jackson:
    default-property-inclusion: NON_EMPTY

server:
  port: 8080
  servlet:
    context-path: /api/v1

mybatis:
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    root: debug
    kirimaru: trace
    org.springframework.security: trace