name: Java CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v3
      - name: Cache gradle modules
        uses: actions/cache@v3
        env:
          cache-name: cache-gradle-modules
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
              ${{ inputs.runner-os }}-gradle-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: sudo
        run: sudo chmod +x ./gradlew
      - name: Build with Gradle
        env:
          GITHUB: true
        run: ./gradlew test

      - if: always()
        name: Upload test result
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: kirimaru-backend/build/reports/**/*
      - name: testReport
        run: ./gradlew jacocoTestReport
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
